language: python
python:
  - "2.7"
before_script:
  - npm install -g npm
  - npm install -g gulp
install:
  - pip install cookiecutter
  - cookiecutter . --no-input
  - cd piedpiper
  - npm install
script:
  - npm run build
notifications:
  email: false

sudo: false

matrix:
  fast_finish: true