{{cookiecutter.insights_platform_app_display_name}}:
  title: {{cookiecutter.insights_platform_app_name}}
  api:
    versions:
      - {{cookiecutter.insights_platform_api_version}}
  deployment_repo: https://github.com/{{cookiecutter.github_organization_name}}/{{cookiecutter.github_repository_name}}.git
  # this next line should only appear if {{cookiecutter.insights_platform_isBeta}} is true
  isBeta: true
